# Generated by Django 5.2.5 on 2025-08-20 13:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название альбома"),
                ),
                (
                    "release_year",
                    models.PositiveIntegerField(
                        help_text="Год официального релиза альбома",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1900, message="Год не может быть раньше 1900"
                            )
                        ],
                        verbose_name="Год выпуска",
                    ),
                ),
            ],
            options={
                "verbose_name": "Альбом",
                "verbose_name_plural": "Альбомы",
                "ordering": ["-release_year", "title"],
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Полное имя или название музыкальной группы",
                        max_length=255,
                        unique=True,
                        verbose_name="Имя исполнителя",
                    ),
                ),
            ],
            options={
                "verbose_name": "Исполнитель",
                "verbose_name_plural": "Исполнители",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AlbumSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "track_number",
                    models.PositiveIntegerField(
                        help_text="Позиция песни в альбоме",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Порядковый номер",
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="album_songs",
                        to="music.album",
                        verbose_name="Альбом",
                    ),
                ),
            ],
            options={
                "verbose_name": "Песня в альбоме",
                "verbose_name_plural": "Песни в альбомах",
                "ordering": ["album", "track_number"],
            },
        ),
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="music.artist",
                verbose_name="Исполнитель",
            ),
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Название песни"
                    ),
                ),
                (
                    "albums",
                    models.ManyToManyField(
                        related_name="songs",
                        through="music.AlbumSong",
                        to="music.album",
                        verbose_name="Альбомы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Песня",
                "verbose_name_plural": "Песни",
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="albumsong",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="song_albums",
                to="music.song",
                verbose_name="Песня",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="album",
            unique_together={("artist", "title")},
        ),
        migrations.AddConstraint(
            model_name="albumsong",
            constraint=models.UniqueConstraint(
                fields=("album", "track_number"), name="unique_album_track_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="albumsong",
            constraint=models.UniqueConstraint(
                fields=("album", "song"), name="unique_album_song"
            ),
        ),
    ]
